<?php
// include_once("conexion.php");
$conn = require_once('conexion.php');


/* $tipoDedocumento = trim($_POST["tipoDedocumento"]);
$numeroDeDocumento = trim($_POST["numeroDeDocumento"]);
$primerApellido = trim($_POST["PrimerApellido"]);
$segundoApellido = trim($_POST["segundoApellido"]);
$primerNombre = trim($_POST["primeroNombre"]);
$segundoNombre = trim($_POST["segundoNombre"]);
$area = trim($_POST["area"]);
$direccion = trim($_POST["direccion"]);
$interior = trim($_POST["flexRadioDefault"]);
$municipioRecidencia = trim($_POST["municipioRecidencia"]);
$barrio = trim($_POST["barrio"]);
$sedeLaboral = trim($_POST["sedeLaboral"]);
$telefonoFijo = trim($_POST["telefono"]);
$movil = trim($_POST["movil"]);
$telefonoEmergencia = trim($_POST["telefonoEmergencia"]);
$correo = trim($_POST["correo"]);
$fechaNacimiento = trim($_POST["fechaNacimiento"]);
$genero = trim($_POST["genero"]);
$idiomas = trim($_POST["idiomas"]);
$numeroDeDireccion = trim($_POST["numeroVia"]); */

$AutorizaTratamiento = trim($_POST["autorizacion"]);
$Fk_TipoDocumento = trim($_POST["tipoDedocumento"]);
$Pk_NumeroDocumento = trim($_POST["numeroDeDocumento"]) ;
$PrimerApellido =  trim($_POST["PrimerApellido"]);
$SegundoApellido = trim($_POST["segundoApellido"]);
$PrimerNombre = trim($_POST["primeroNombre"]);
$SegundoNombre =  trim($_POST["segundoNombre"]);
$Fk_Sede =  trim($_POST["sedeLaboral"]);
$Fk_Area = trim($_POST["area"]);
$Fk_TipoVia = trim($_POST["direccion"]);
$NumeroVia = trim($_POST["numeroViaUno"]); //revisar
$Interior = trim($_POST["flexRadioDefault"]);
$Municipio = trim($_POST["municipioRecidencia"]);
$Barrios = trim($_POST["barrio"]);
$Telefonofijo = trim($_POST["telefono"]);
$Movil = trim($_POST["movil"]);
$TelefonoEmergencia = trim($_POST["telefonoEmergencia"]);
$CorreoElectronico = trim($_POST["correo"]);
$FechaNacimiento = trim($_POST["fechaNacimiento"]);
$Fk_Genero = trim($_POST["genero"]);
$Fk_idioma =  trim($_POST["idiomas"]);
$Guion = "-";

$query = $conn->prepare('call spInsertarUsuario(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
// $query = $conn ->prepare('INSERT INTO personal_almacontact  VALUES ("?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?")');
echo "<br>";
var_dump($AutorizaTratamiento);
echo "<br>";
var_dump($Fk_TipoDocumento);
echo "<br>";
var_dump($Pk_NumeroDocumento);
echo "<br>";
var_dump($PrimerApellido);
echo "<br>";
var_dump($SegundoApellido);
echo "<br>";
var_dump($PrimerNombre);
echo "<br>";
var_dump($SegundoNombre);
echo "<br>";
var_dump($Fk_Sede);
echo "<br>";
var_dump($Fk_Area);
echo "<br>";
var_dump($Fk_TipoVia);
echo "<br>";
var_dump($Interior);
echo "<br>";
var_dump($NumeroVia);
echo "<br>";
var_dump($Municipio);
echo "<br>";
var_dump($Barrios);
echo "<br>";
var_dump($Telefonofijo);
echo "<br>";
var_dump($TelefonoEmergencia);
echo "<br>";
var_dump($CorreoElectronico);
echo "<br>";
var_dump($FechaNacimiento);
echo "<br>";
var_dump($Fk_Genero);
echo "<br>";
var_dump($Fk_idioma);
echo "<br>";
var_dump($Guion);
echo "<br>";
var_dump($Movil);

$query->bindParam(1, $AutorizaTratamiento, PDO::PARAM_STR);
$query->bindParam(2, $Fk_TipoDocumento, PDO::PARAM_INT);
$query->bindParam(3,  $Pk_NumeroDocumento, PDO::PARAM_STR);
$query->bindParam(4, $PrimerApellido, PDO::PARAM_STR);
$query->bindParam(5, $SegundoApellido, PDO::PARAM_STR); 
$query->bindParam(6, $PrimerNombre, PDO::PARAM_STR);
$query->bindParam(7, $SegundoNombre, PDO::PARAM_STR);
$query->bindParam(8, $Fk_Sede, PDO::PARAM_INT);
$query->bindParam(9, $Fk_Area, PDO::PARAM_INT);
$query->bindParam(10, $Fk_TipoVia, PDO::PARAM_INT);
$query->bindParam(11, $NumeroVia, PDO::PARAM_STR);
$query->bindParam(12, $Guion, PDO::PARAM_STR);
$query->bindParam(13, $Interior, PDO::PARAM_STR);
$query->bindParam(14, $Municipio, PDO::PARAM_STR);
$query->bindParam(15, $Barrios, PDO::PARAM_STR);
$query->bindParam(16, $Telefonofijo, PDO::PARAM_INT);
$query->bindParam(17, $Movil, PDO::PARAM_INT);
$query->bindParam(18, $TelefonoEmergencia, PDO::PARAM_INT);
$query->bindParam(19, $CorreoElectronico, PDO::PARAM_STR);
$query->bindParam(20, $FechaNacimiento, PDO::PARAM_STR);
$query->bindParam(21, $Fk_Genero, PDO::PARAM_INT);
$query->bindParam(22, $Fk_idioma, PDO::PARAM_INT);

$query->execute();

echo '<script> alert("registro exitoso")</script>';
